version: '3'
services:
  top-api:
    image: top-api:latest
    restart: always
    container_name: top-api
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env

  top-api.mongo:
    image: mongo
    restart: always
    container_name: top-api.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017

    volumes:
      - ./mongo-data:/data/db
