name: Publish Docker

on:
	push:
		branches: [ main ]

jobs:
	build:
		runs-on: ubuntu-latest
		step:
			- uses: actions/checkout@v3
			- name: Publist to registry
			  uses: elgohr/Publish-Docker-Github-Action@v5
			  with:
					registry: docker.pkg.github.com
				  name: hdocker.pkg.github.com/Deadmanch/top-api/top-api
				  username: ${{ secrets.DOCKER_USERNAME }}
				  password: ${{ secrets.DOCKER_PASSWORD }}
					tags: 'develop'